// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testing.proxies;

public class Testing
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testingMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Testing.Testing";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Input("Input"),
		Action("Action"),
		ReturnValue("ReturnValue");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Testing(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Testing.Testing"));
	}

	protected Testing(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testingMendixObject)
	{
		if (testingMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Testing.Testing", testingMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Testing.Testing");

		this.testingMendixObject = testingMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Testing.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static testing.proxies.Testing initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testing.proxies.Testing.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testing.proxies.Testing initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testing.proxies.Testing(context, mendixObject);
	}

	public static testing.proxies.Testing load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testing.proxies.Testing.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Input
	 */
	public final java.lang.String getInput()
	{
		return getInput(getContext());
	}

	/**
	 * @param context
	 * @return value of Input
	 */
	public final java.lang.String getInput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Input.toString());
	}

	/**
	 * Set value of Input
	 * @param input
	 */
	public final void setInput(java.lang.String input)
	{
		setInput(getContext(), input);
	}

	/**
	 * Set value of Input
	 * @param context
	 * @param input
	 */
	public final void setInput(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String input)
	{
		getMendixObject().setValue(context, MemberNames.Input.toString(), input);
	}

	/**
	 * Set value of Action
	 * @param action
	 */
	public final testing.proxies.Actions getAction()
	{
		return getAction(getContext());
	}

	/**
	 * @param context
	 * @return value of Action
	 */
	public final testing.proxies.Actions getAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Action.toString());
		if (obj == null)
			return null;

		return testing.proxies.Actions.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Action
	 * @param action
	 */
	public final void setAction(testing.proxies.Actions action)
	{
		setAction(getContext(), action);
	}

	/**
	 * Set value of Action
	 * @param context
	 * @param action
	 */
	public final void setAction(com.mendix.systemwideinterfaces.core.IContext context, testing.proxies.Actions action)
	{
		if (action != null)
			getMendixObject().setValue(context, MemberNames.Action.toString(), action.toString());
		else
			getMendixObject().setValue(context, MemberNames.Action.toString(), null);
	}

	/**
	 * @return value of ReturnValue
	 */
	public final java.lang.String getReturnValue()
	{
		return getReturnValue(getContext());
	}

	/**
	 * @param context
	 * @return value of ReturnValue
	 */
	public final java.lang.String getReturnValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReturnValue.toString());
	}

	/**
	 * Set value of ReturnValue
	 * @param returnvalue
	 */
	public final void setReturnValue(java.lang.String returnvalue)
	{
		setReturnValue(getContext(), returnvalue);
	}

	/**
	 * Set value of ReturnValue
	 * @param context
	 * @param returnvalue
	 */
	public final void setReturnValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String returnvalue)
	{
		getMendixObject().setValue(context, MemberNames.ReturnValue.toString(), returnvalue);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testingMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testing.proxies.Testing that = (testing.proxies.Testing) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Testing.Testing";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
