// This file was generated by Mendix Modeler 7.13.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testing.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the Testing module
	public static void createTestObject(IContext context, testing.proxies.Actions _actions, java.lang.String _input)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Actions", _actions == null ? null : _actions.name());
			params.put("Input", _input);
			Core.execute(context, "Testing.CreateTestObject", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void executeAction(IContext context, testing.proxies.Testing _testing)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Testing", _testing == null ? null : _testing.getMendixObject());
			Core.execute(context, "Testing.ExecuteAction", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void getCookie(IContext context, testing.proxies.Testing _testing)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Testing", _testing == null ? null : _testing.getMendixObject());
			Core.execute(context, "Testing.GetCookie", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void getHeader(IContext context, testing.proxies.Testing _testing)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Testing", _testing == null ? null : _testing.getMendixObject());
			Core.execute(context, "Testing.GetHeader", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void runGetCookie(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "Testing.RunGetCookie", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void runGetHeader(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "Testing.RunGetHeader", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}